name: MacOS
on: workflow_dispatch
jobs:
  iOS:
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4
      - name: Extract Files
        run: |
          7z x compile_fix.zip

      - name: Install Libraries
        run: |
          mkdir ~/haxelib
          haxelib setup ~/haxelib 
          haxelib install hmm --quiet
          haxelib run hmm install --quiet

      - name: Compile
        run: haxelib run lime build mac -D NOVIDEO -final

      - name: Upload Artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@main
        with:
          name: macBuild
          path: export/release/macos/bin/*
          if-no-files-found: error
